# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.9.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs

# Pipeline parameters
parameters:
  type_testing:
    type: string
    default: "regression"
  test_env:
    type: string
    default: "production"

jobs:
  notify:

    # Job parameters
    parameters:
      type_testing:
        type: string
        default: "regression"
      test_env:
        type: string
        default: "production"

    docker:
      # - image: cimg/base:current # this image does not have Node.js installed
      - image: cimg/node:lts
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      # Run tests using reporters defined in playwright.config.js
      - run:
          name: Run Playwright tests
          command: |
            npx cross-env TEST_ENV=<<parameters.test_env>> npx playwright test --grep "<<parameters.type_testing>>"
            EXIT_CODE=$?
            exit 0


      - store_artifacts:
          path: playwright-report
          destination: playwright-report

      # Store JUnit XML so CircleCI shows test results
      - store_test_results:
          path: test-results

      # SIMPLE + RELIABLE: Use CircleCI artifacts page instead of direct HTML
      - run:
          name: Set Playwright report URL (CircleCI artifacts page)
          command: |
            echo "REPORT_URL=${CIRCLE_BUILD_URL}/artifacts" >> $BASH_ENV

      # Slack notification with counts + direct HTML report link
      - slack/notify:
          event: always
          channel: C0A3G0YNS9Y


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  send-notification-to-slack:

    # For project settings
    jobs:
      - notify:
          type_testing: << pipeline.parameters.type_testing >>
          test_env: << pipeline.parameters.test_env >>
          # filters:
          #   branches:
          #     only: master

# The cron job is executed in CircleCI's configuration, not here.